language: python
python:
    - "3.6.8"
#before_install:
#    - pip install pytest pytest-cov
#    - pip install codecov
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n multiplex python=$TRAVIS_PYTHON_VERSION --no-default-packages
  - conda activate multiplex
  - conda install -c conda-forge fenics=2018.1.0 mshr=2018.1.0 matplotlib
  - conda install -c conda-forge pytest pytest-cov
  - conda install -c conda-forge pyyaml
  - conda install -c conda-forge codecov
  #- python setup.py install
  - pip freeze

script:
  - pytest --cov=multiplex/

after_success:
  - codecov
