language: python
python:
    - "3.6.8"

install:

  # Install Conda
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Create execution enviroment
  - conda create -q -n multiplex python=$TRAVIS_PYTHON_VERSION --no-default-packages
  - conda activate multiplex
  - conda install -c conda-forge fenics=2018.1.0 mshr=2018.1.0 matplotlib pyyaml pytest pytest-cov codecov
  - pip freeze

script:
  - pytest --cov=multiplex/

after_success:
  - codecov
