---
# Solver parametes (multiplex.meshelement)
snaps: 40                             # number of snap shoots
iterations: 50                        # number of iterations
time_step (s): 1e-2                   # time step in seconds
viscosity (Pa): 8.9e-04               # dynamic viscosity in Pa
mass_density (kg/cubic meter): 997    # mass density in kg per cubic meter
inlet_width (m): 0.032                # inlet width in meter
reynolds_number: 10                   # Reynolds number (dimensionless)
mesh_resolution: 10                   # resolution of the mesh
scale: 10                             # for meter:      scale=1,
                                      # for decimeter:  scale=10,
                                      # for centimeter: scale=100,
                                      # for milimeter:  scale=1000,

# Manifold parametes (multiplex.bifurcatedmanifold)
inlet_length (m): 0.07                # inlet length in meter
device_to_device_distance (m): 0.05   # device to device distance in meters
number_of_layers: 3                   # different manifold layers
gamma: 0.8                            # shrinking factor for each layer
manifold_type: "rectangular"          # type of the manifolds
origin:                               # origin of the manifold (center of the inlet)
  - 0                                 # x cordinate of origin
  - 0                                 # y cordinate of origin